export type ConcernEntry = { name: string; ingredients: string[] };

export const SKIN_CONCERNS: ConcernEntry[] = [
  { name: "Acne", ingredients: ["Salicylic Acid", "Niacinamide", "Zinc PCA"] },
  { name: "Pimples", ingredients: ["Benzoyl Peroxide", "Tea Tree Oil", "Sulfur"] },
  { name: "Acne Scars", ingredients: ["Azelaic Acid", "Retinol", "Niacinamide"] },
  { name: "Dark Spots", ingredients: ["Alpha Arbutin", "Tranexamic Acid", "Vitamin C"] },
  { name: "Hyperpigmentation", ingredients: ["Kojic Acid", "Alpha Arbutin", "Niacinamide"] },
  { name: "Melasma", ingredients: ["Tranexamic Acid", "Azelaic Acid", "Vitamin C"] },
  { name: "Uneven Skin Tone", ingredients: ["Vitamin C", "Niacinamide", "Licorice Extract"] },
  { name: "Dull Skin", ingredients: ["Vitamin C", "Glycolic Acid", "Lactic Acid"] },
  { name: "Dehydrated Skin", ingredients: ["Hyaluronic Acid", "Glycerin", "Panthenol"] },
  { name: "Dry Skin", ingredients: ["Ceramides", "Squalane", "Shea Butter"] },
  { name: "Oily Skin", ingredients: ["Niacinamide", "Zinc PCA", "Green Tea"] },
  { name: "Combination Skin", ingredients: ["Niacinamide", "Hyaluronic Acid"] },
  { name: "Sensitive Skin", ingredients: ["Centella Asiatica", "Allantoin", "Oat Extract"] },
  { name: "Redness", ingredients: ["Centella", "Panthenol", "Bisabolol"] },
  { name: "Rosacea-Prone Skin", ingredients: ["Azelaic Acid", "Centella", "Allantoin"] },
  { name: "Enlarged Pores", ingredients: ["Niacinamide", "Salicylic Acid", "Retinol"] },
  { name: "Blackheads", ingredients: ["Salicylic Acid", "Clay", "Niacinamide"] },
  { name: "Whiteheads", ingredients: ["Salicylic Acid", "Sulfur"] },
  { name: "Fine Lines", ingredients: ["Retinol", "Peptides", "Bakuchiol"] },
  { name: "Wrinkles", ingredients: ["Retinal", "Peptides", "Vitamin C"] },
  { name: "Loss of Firmness", ingredients: ["Peptides", "Collagen Boosters", "Retinol"] },
  { name: "Sagging Skin", ingredients: ["Peptides", "Copper Peptides"] },
  { name: "Rough Texture", ingredients: ["Glycolic Acid", "Lactic Acid", "PHA"] },
  { name: "Large Pores", ingredients: ["Niacinamide", "Retinol"] },
  { name: "Sun Damage", ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"] },
  { name: "UV Damage", ingredients: ["Antioxidants", "DNA Repair Enzymes"] },
  { name: "Barrier Damage", ingredients: ["Ceramides", "Cholesterol", "Fatty Acids"] },
  { name: "Irritation", ingredients: ["Panthenol", "Centella", "Madecassoside"] },
  { name: "Itchy Skin", ingredients: ["Colloidal Oatmeal", "Ceramides"] },
  { name: "Flaky Skin", ingredients: ["Urea", "Ceramides", "Squalane"] },
  { name: "Excess Sebum", ingredients: ["Zinc PCA", "Niacinamide"] },
  { name: "Shine Control", ingredients: ["Silica", "Niacinamide"] },
  { name: "Eye Dark Circles", ingredients: ["Caffeine", "Vitamin K", "Niacinamide"] },
  { name: "Eye Puffiness", ingredients: ["Caffeine", "Peptides"] },
  { name: "Chapped Lips", ingredients: ["Shea Butter", "Lanolin", "Ceramides"] },
  { name: "Neck Pigmentation", ingredients: ["Alpha Arbutin", "Tranexamic Acid"] },
  { name: "Forehead Lines", ingredients: ["Retinol", "Peptides"] },
  { name: "Smile Lines", ingredients: ["Peptides", "Hyaluronic Acid"] },
  { name: "Skin Elasticity Loss", ingredients: ["Copper Peptides", "Retinol"] },
  { name: "Anti-Aging Overall", ingredients: ["Retinal", "Vitamin C", "Niacinamide", "Peptides", "Ceramides", "Sunscreen"] },
];

export type IngredientInfo = { name: string; emoji: string; benefit: string; goodFor: string[] };

export const CORE_INGREDIENTS: IngredientInfo[] = [
  { name: "Niacinamide", emoji: "✨", benefit: "Balances oil, evens tone, refines pores", goodFor: ["Oily", "Pores", "Uneven tone"] },
  { name: "Hyaluronic Acid", emoji: "💧", benefit: "Deep hydration, plumps skin", goodFor: ["Dehydrated", "All types"] },
  { name: "Ceramides", emoji: "🧱", benefit: "Repairs & strengthens skin barrier", goodFor: ["Dry", "Sensitive", "Barrier"] },
  { name: "Retinal / Retinol", emoji: "🌙", benefit: "Anti-aging, cell turnover", goodFor: ["Wrinkles", "Acne scars"] },
  { name: "Bakuchiol", emoji: "🌿", benefit: "Gentle retinol alternative", goodFor: ["Sensitive", "Fine lines"] },
  { name: "Vitamin C", emoji: "🍊", benefit: "Brightens, antioxidant, evens tone", goodFor: ["Dull", "Dark spots"] },
  { name: "Vitamin E", emoji: "🌻", benefit: "Antioxidant, soothes & protects", goodFor: ["Sun damage", "Dry"] },
  { name: "Ferulic Acid", emoji: "🛡️", benefit: "Boosts Vitamin C, fights free radicals", goodFor: ["Sun damage"] },
  { name: "Salicylic Acid", emoji: "🧴", benefit: "Unclogs pores, exfoliates deep", goodFor: ["Acne", "Blackheads"] },
  { name: "Glycolic Acid", emoji: "⚡", benefit: "Resurfaces, brightens texture", goodFor: ["Dull", "Rough texture"] },
  { name: "Lactic Acid", emoji: "🥛", benefit: "Gentle exfoliation + hydration", goodFor: ["Dry", "Dull"] },
  { name: "PHA (Gluconolactone)", emoji: "🌸", benefit: "Mildest exfoliant, hydrating", goodFor: ["Sensitive", "Texture"] },
  { name: "Alpha Arbutin", emoji: "🎯", benefit: "Targets dark spots safely", goodFor: ["Pigmentation"] },
  { name: "Tranexamic Acid", emoji: "🔬", benefit: "Fades melasma & stubborn marks", goodFor: ["Melasma", "Dark spots"] },
  { name: "Kojic Acid", emoji: "🍄", benefit: "Skin brightening", goodFor: ["Hyperpigmentation"] },
  { name: "Azelaic Acid", emoji: "🌾", benefit: "Calms redness, fades marks", goodFor: ["Rosacea", "Acne scars"] },
  { name: "Zinc PCA", emoji: "⚗️", benefit: "Controls sebum, calms skin", goodFor: ["Oily", "Acne"] },
  { name: "Panthenol (B5)", emoji: "🕊️", benefit: "Soothes, heals, hydrates", goodFor: ["Irritation", "Redness"] },
  { name: "Centella Asiatica", emoji: "🍃", benefit: "Anti-inflammatory, calming", goodFor: ["Sensitive", "Redness"] },
  { name: "Madecassoside", emoji: "🌱", benefit: "Repairs & soothes irritation", goodFor: ["Barrier", "Irritation"] },
  { name: "Allantoin", emoji: "☁️", benefit: "Softens & soothes skin", goodFor: ["Sensitive"] },
  { name: "Peptides", emoji: "🧬", benefit: "Firms & rebuilds collagen", goodFor: ["Aging", "Firmness"] },
  { name: "Copper Peptides", emoji: "🔗", benefit: "Advanced anti-aging repair", goodFor: ["Sagging", "Elasticity"] },
  { name: "Squalane", emoji: "🫒", benefit: "Lightweight nourishing oil", goodFor: ["Dry", "All types"] },
  { name: "Glycerin", emoji: "💦", benefit: "Draws moisture into skin", goodFor: ["All types"] },
];

export const SKIN_BASICS: { step: string; title: string; desc: string; emoji: string }[] = [
  { step: "1", emoji: "🧼", title: "Cleanse", desc: "Gentle cleanser AM & PM to remove dirt and excess oil." },
  { step: "2", emoji: "🌊", title: "Tone / Hydrate", desc: "Optional toner or essence to prep and hydrate skin." },
  { step: "3", emoji: "💧", title: "Serum", desc: "Targeted actives — Vitamin C (AM) or Retinol (PM)." },
  { step: "4", emoji: "🧴", title: "Moisturize", desc: "Lock in hydration and support your skin barrier." },
  { step: "5", emoji: "☀️", title: "Sunscreen (AM)", desc: "SPF 30+ every morning — the #1 anti-aging step." },
];
