/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TipsIndexRouteImport } from './routes/tips.index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as RemindersIndexRouteImport } from './routes/reminders.index'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations.index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as TipsIngredientsRouteImport } from './routes/tips.ingredients'
import { Route as TipsExpertsRouteImport } from './routes/tips.experts'
import { Route as TipsConcernsRouteImport } from './routes/tips.concerns'
import { Route as TipsCategoriesRouteImport } from './routes/tips.categories'
import { Route as TipsBasicsRouteImport } from './routes/tips.basics'
import { Route as ShopTrackRouteImport } from './routes/shop.track'
import { Route as ShopReviewRouteImport } from './routes/shop.review'
import { Route as ShopPaymentRouteImport } from './routes/shop.payment'
import { Route as ShopOrderRouteImport } from './routes/shop.order'
import { Route as ShopDeliveredRouteImport } from './routes/shop.delivered'
import { Route as ShopConfirmedRouteImport } from './routes/shop.confirmed'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopAddressRouteImport } from './routes/shop.address'
import { Route as ShopAddedRouteImport } from './routes/shop.added'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsPersonalRouteImport } from './routes/settings.personal'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as RemindersNewRouteImport } from './routes/reminders.new'
import { Route as RemindersCalendarRouteImport } from './routes/reminders.calendar'
import { Route as RemindersIdRouteImport } from './routes/reminders.$id'
import { Route as RecommendationsShareRouteImport } from './routes/recommendations.share'
import { Route as RecommendationsSaveRouteImport } from './routes/recommendations.save'
import { Route as RecommendationsRoutineRouteImport } from './routes/recommendations.routine'
import { Route as RecommendationsProductsRouteImport } from './routes/recommendations.products'
import { Route as HistoryCompareRouteImport } from './routes/history.compare'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as FavoritesRoutinesRouteImport } from './routes/favorites.routines'
import { Route as FavoritesProductsRouteImport } from './routes/favorites.products'
import { Route as FavoritesExpertsRouteImport } from './routes/favorites.experts'
import { Route as FavoritesCollectionsRouteImport } from './routes/favorites.collections'
import { Route as FavoritesArticlesRouteImport } from './routes/favorites.articles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as TipsExpertsIdRouteImport } from './routes/tips.experts.$id'
import { Route as TipsArticleSlugRouteImport } from './routes/tips.article.$slug'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'
import { Route as ShopPaymentCardRouteImport } from './routes/shop.payment.card'
import { Route as RemindersIdSnoozeRouteImport } from './routes/reminders.$id.snooze'
import { Route as ApiCronRemindersRouteImport } from './routes/api.cron.reminders'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin.revenue'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminExpertsRouteImport } from './routes/_authenticated/admin.experts'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminReportsIndexRouteImport } from './routes/_authenticated/admin.reports.index'
import { Route as AuthenticatedAdminReportsIdRouteImport } from './routes/_authenticated/admin.reports.$id'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsIndexRoute = TipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TipsRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RemindersRoute,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecommendationsRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FavoritesRoute,
} as any)
const TipsIngredientsRoute = TipsIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => TipsRoute,
} as any)
const TipsExpertsRoute = TipsExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => TipsRoute,
} as any)
const TipsConcernsRoute = TipsConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => TipsRoute,
} as any)
const TipsCategoriesRoute = TipsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => TipsRoute,
} as any)
const TipsBasicsRoute = TipsBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => TipsRoute,
} as any)
const ShopTrackRoute = ShopTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReviewRoute = ShopReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPaymentRoute = ShopPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderRoute = ShopOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ShopRoute,
} as any)
const ShopDeliveredRoute = ShopDeliveredRouteImport.update({
  id: '/delivered',
  path: '/delivered',
  getParentRoute: () => ShopRoute,
} as any)
const ShopConfirmedRoute = ShopConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAddressRoute = ShopAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAddedRoute = ShopAddedRouteImport.update({
  id: '/added',
  path: '/added',
  getParentRoute: () => ShopRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalRoute = SettingsPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNewRoute = RemindersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RemindersRoute,
} as any)
const RemindersCalendarRoute = RemindersCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => RemindersRoute,
} as any)
const RemindersIdRoute = RemindersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RemindersRoute,
} as any)
const RecommendationsShareRoute = RecommendationsShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => RecommendationsRoute,
} as any)
const RecommendationsSaveRoute = RecommendationsSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => RecommendationsRoute,
} as any)
const RecommendationsRoutineRoute = RecommendationsRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => RecommendationsRoute,
} as any)
const RecommendationsProductsRoute = RecommendationsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => RecommendationsRoute,
} as any)
const HistoryCompareRoute = HistoryCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const FavoritesRoutinesRoute = FavoritesRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesProductsRoute = FavoritesProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesExpertsRoute = FavoritesExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesCollectionsRoute = FavoritesCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesArticlesRoute = FavoritesArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => FavoritesRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const TipsExpertsIdRoute = TipsExpertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TipsExpertsRoute,
} as any)
const TipsArticleSlugRoute = TipsArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => TipsRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPaymentCardRoute = ShopPaymentCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ShopPaymentRoute,
} as any)
const RemindersIdSnoozeRoute = RemindersIdSnoozeRouteImport.update({
  id: '/snooze',
  path: '/snooze',
  getParentRoute: () => RemindersIdRoute,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpertsRoute =
  AuthenticatedAdminExpertsRouteImport.update({
    id: '/experts',
    path: '/experts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsIndexRoute =
  AuthenticatedAdminReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsIdRoute =
  AuthenticatedAdminReportsIdRouteImport.update({
    id: '/reports/$id',
    path: '/reports/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/reminders': typeof RemindersRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tips': typeof TipsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/favorites/articles': typeof FavoritesArticlesRoute
  '/favorites/collections': typeof FavoritesCollectionsRoute
  '/favorites/experts': typeof FavoritesExpertsRoute
  '/favorites/products': typeof FavoritesProductsRoute
  '/favorites/routines': typeof FavoritesRoutinesRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/compare': typeof HistoryCompareRoute
  '/recommendations/products': typeof RecommendationsProductsRoute
  '/recommendations/routine': typeof RecommendationsRoutineRoute
  '/recommendations/save': typeof RecommendationsSaveRoute
  '/recommendations/share': typeof RecommendationsShareRoute
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/reminders/calendar': typeof RemindersCalendarRoute
  '/reminders/new': typeof RemindersNewRoute
  '/s/$token': typeof STokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/shop/added': typeof ShopAddedRoute
  '/shop/address': typeof ShopAddressRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/confirmed': typeof ShopConfirmedRoute
  '/shop/delivered': typeof ShopDeliveredRoute
  '/shop/order': typeof ShopOrderRoute
  '/shop/payment': typeof ShopPaymentRouteWithChildren
  '/shop/review': typeof ShopReviewRoute
  '/shop/track': typeof ShopTrackRoute
  '/tips/basics': typeof TipsBasicsRoute
  '/tips/categories': typeof TipsCategoriesRoute
  '/tips/concerns': typeof TipsConcernsRoute
  '/tips/experts': typeof TipsExpertsRouteWithChildren
  '/tips/ingredients': typeof TipsIngredientsRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/reminders/$id/snooze': typeof RemindersIdSnoozeRoute
  '/shop/payment/card': typeof ShopPaymentCardRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/tips/article/$slug': typeof TipsArticleSlugRoute
  '/tips/experts/$id': typeof TipsExpertsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favorites/articles': typeof FavoritesArticlesRoute
  '/favorites/collections': typeof FavoritesCollectionsRoute
  '/favorites/experts': typeof FavoritesExpertsRoute
  '/favorites/products': typeof FavoritesProductsRoute
  '/favorites/routines': typeof FavoritesRoutinesRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/compare': typeof HistoryCompareRoute
  '/recommendations/products': typeof RecommendationsProductsRoute
  '/recommendations/routine': typeof RecommendationsRoutineRoute
  '/recommendations/save': typeof RecommendationsSaveRoute
  '/recommendations/share': typeof RecommendationsShareRoute
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/reminders/calendar': typeof RemindersCalendarRoute
  '/reminders/new': typeof RemindersNewRoute
  '/s/$token': typeof STokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/shop/added': typeof ShopAddedRoute
  '/shop/address': typeof ShopAddressRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/confirmed': typeof ShopConfirmedRoute
  '/shop/delivered': typeof ShopDeliveredRoute
  '/shop/order': typeof ShopOrderRoute
  '/shop/payment': typeof ShopPaymentRouteWithChildren
  '/shop/review': typeof ShopReviewRoute
  '/shop/track': typeof ShopTrackRoute
  '/tips/basics': typeof TipsBasicsRoute
  '/tips/categories': typeof TipsCategoriesRoute
  '/tips/concerns': typeof TipsConcernsRoute
  '/tips/experts': typeof TipsExpertsRouteWithChildren
  '/tips/ingredients': typeof TipsIngredientsRoute
  '/favorites': typeof FavoritesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/tips': typeof TipsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/reminders/$id/snooze': typeof RemindersIdSnoozeRoute
  '/shop/payment/card': typeof ShopPaymentCardRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/tips/article/$slug': typeof TipsArticleSlugRoute
  '/tips/experts/$id': typeof TipsExpertsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/admin/reports': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/reminders': typeof RemindersRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tips': typeof TipsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/favorites/articles': typeof FavoritesArticlesRoute
  '/favorites/collections': typeof FavoritesCollectionsRoute
  '/favorites/experts': typeof FavoritesExpertsRoute
  '/favorites/products': typeof FavoritesProductsRoute
  '/favorites/routines': typeof FavoritesRoutinesRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/compare': typeof HistoryCompareRoute
  '/recommendations/products': typeof RecommendationsProductsRoute
  '/recommendations/routine': typeof RecommendationsRoutineRoute
  '/recommendations/save': typeof RecommendationsSaveRoute
  '/recommendations/share': typeof RecommendationsShareRoute
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/reminders/calendar': typeof RemindersCalendarRoute
  '/reminders/new': typeof RemindersNewRoute
  '/s/$token': typeof STokenRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/personal': typeof SettingsPersonalRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/shop/added': typeof ShopAddedRoute
  '/shop/address': typeof ShopAddressRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/confirmed': typeof ShopConfirmedRoute
  '/shop/delivered': typeof ShopDeliveredRoute
  '/shop/order': typeof ShopOrderRoute
  '/shop/payment': typeof ShopPaymentRouteWithChildren
  '/shop/review': typeof ShopReviewRoute
  '/shop/track': typeof ShopTrackRoute
  '/tips/basics': typeof TipsBasicsRoute
  '/tips/categories': typeof TipsCategoriesRoute
  '/tips/concerns': typeof TipsConcernsRoute
  '/tips/experts': typeof TipsExpertsRouteWithChildren
  '/tips/ingredients': typeof TipsIngredientsRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/tips/': typeof TipsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/experts': typeof AuthenticatedAdminExpertsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/reminders/$id/snooze': typeof RemindersIdSnoozeRoute
  '/shop/payment/card': typeof ShopPaymentCardRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/tips/article/$slug': typeof TipsArticleSlugRoute
  '/tips/experts/$id': typeof TipsExpertsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
  '/_authenticated/admin/reports/': typeof AuthenticatedAdminReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/history'
    | '/recommendations'
    | '/reminders'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/tips'
    | '/admin'
    | '/favorites/articles'
    | '/favorites/collections'
    | '/favorites/experts'
    | '/favorites/products'
    | '/favorites/routines'
    | '/history/$id'
    | '/history/compare'
    | '/recommendations/products'
    | '/recommendations/routine'
    | '/recommendations/save'
    | '/recommendations/share'
    | '/reminders/$id'
    | '/reminders/calendar'
    | '/reminders/new'
    | '/s/$token'
    | '/settings/notifications'
    | '/settings/personal'
    | '/settings/preferences'
    | '/settings/security'
    | '/shop/added'
    | '/shop/address'
    | '/shop/cart'
    | '/shop/confirmed'
    | '/shop/delivered'
    | '/shop/order'
    | '/shop/payment'
    | '/shop/review'
    | '/shop/track'
    | '/tips/basics'
    | '/tips/categories'
    | '/tips/concerns'
    | '/tips/experts'
    | '/tips/ingredients'
    | '/favorites/'
    | '/history/'
    | '/recommendations/'
    | '/reminders/'
    | '/settings/'
    | '/shop/'
    | '/tips/'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/coupons'
    | '/admin/experts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/revenue'
    | '/admin/users'
    | '/api/cron/reminders'
    | '/reminders/$id/snooze'
    | '/shop/payment/card'
    | '/shop/product/$id'
    | '/tips/article/$slug'
    | '/tips/experts/$id'
    | '/admin/'
    | '/admin/reports/$id'
    | '/admin/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/auth'
    | '/dashboard'
    | '/scan'
    | '/sitemap.xml'
    | '/favorites/articles'
    | '/favorites/collections'
    | '/favorites/experts'
    | '/favorites/products'
    | '/favorites/routines'
    | '/history/$id'
    | '/history/compare'
    | '/recommendations/products'
    | '/recommendations/routine'
    | '/recommendations/save'
    | '/recommendations/share'
    | '/reminders/$id'
    | '/reminders/calendar'
    | '/reminders/new'
    | '/s/$token'
    | '/settings/notifications'
    | '/settings/personal'
    | '/settings/preferences'
    | '/settings/security'
    | '/shop/added'
    | '/shop/address'
    | '/shop/cart'
    | '/shop/confirmed'
    | '/shop/delivered'
    | '/shop/order'
    | '/shop/payment'
    | '/shop/review'
    | '/shop/track'
    | '/tips/basics'
    | '/tips/categories'
    | '/tips/concerns'
    | '/tips/experts'
    | '/tips/ingredients'
    | '/favorites'
    | '/history'
    | '/recommendations'
    | '/reminders'
    | '/settings'
    | '/shop'
    | '/tips'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/coupons'
    | '/admin/experts'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/revenue'
    | '/admin/users'
    | '/api/cron/reminders'
    | '/reminders/$id/snooze'
    | '/shop/payment/card'
    | '/shop/product/$id'
    | '/tips/article/$slug'
    | '/tips/experts/$id'
    | '/admin'
    | '/admin/reports/$id'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analysis'
    | '/auth'
    | '/dashboard'
    | '/favorites'
    | '/history'
    | '/recommendations'
    | '/reminders'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/tips'
    | '/_authenticated/admin'
    | '/favorites/articles'
    | '/favorites/collections'
    | '/favorites/experts'
    | '/favorites/products'
    | '/favorites/routines'
    | '/history/$id'
    | '/history/compare'
    | '/recommendations/products'
    | '/recommendations/routine'
    | '/recommendations/save'
    | '/recommendations/share'
    | '/reminders/$id'
    | '/reminders/calendar'
    | '/reminders/new'
    | '/s/$token'
    | '/settings/notifications'
    | '/settings/personal'
    | '/settings/preferences'
    | '/settings/security'
    | '/shop/added'
    | '/shop/address'
    | '/shop/cart'
    | '/shop/confirmed'
    | '/shop/delivered'
    | '/shop/order'
    | '/shop/payment'
    | '/shop/review'
    | '/shop/track'
    | '/tips/basics'
    | '/tips/categories'
    | '/tips/concerns'
    | '/tips/experts'
    | '/tips/ingredients'
    | '/favorites/'
    | '/history/'
    | '/recommendations/'
    | '/reminders/'
    | '/settings/'
    | '/shop/'
    | '/tips/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/experts'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/users'
    | '/api/cron/reminders'
    | '/reminders/$id/snooze'
    | '/shop/payment/card'
    | '/shop/product/$id'
    | '/tips/article/$slug'
    | '/tips/experts/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/reports/$id'
    | '/_authenticated/admin/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRouteWithChildren
  HistoryRoute: typeof HistoryRouteWithChildren
  RecommendationsRoute: typeof RecommendationsRouteWithChildren
  RemindersRoute: typeof RemindersRouteWithChildren
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TipsRoute: typeof TipsRouteWithChildren
  STokenRoute: typeof STokenRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips/': {
      id: '/tips/'
      path: '/'
      fullPath: '/tips/'
      preLoaderRoute: typeof TipsIndexRouteImport
      parentRoute: typeof TipsRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof RemindersRoute
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/tips/ingredients': {
      id: '/tips/ingredients'
      path: '/ingredients'
      fullPath: '/tips/ingredients'
      preLoaderRoute: typeof TipsIngredientsRouteImport
      parentRoute: typeof TipsRoute
    }
    '/tips/experts': {
      id: '/tips/experts'
      path: '/experts'
      fullPath: '/tips/experts'
      preLoaderRoute: typeof TipsExpertsRouteImport
      parentRoute: typeof TipsRoute
    }
    '/tips/concerns': {
      id: '/tips/concerns'
      path: '/concerns'
      fullPath: '/tips/concerns'
      preLoaderRoute: typeof TipsConcernsRouteImport
      parentRoute: typeof TipsRoute
    }
    '/tips/categories': {
      id: '/tips/categories'
      path: '/categories'
      fullPath: '/tips/categories'
      preLoaderRoute: typeof TipsCategoriesRouteImport
      parentRoute: typeof TipsRoute
    }
    '/tips/basics': {
      id: '/tips/basics'
      path: '/basics'
      fullPath: '/tips/basics'
      preLoaderRoute: typeof TipsBasicsRouteImport
      parentRoute: typeof TipsRoute
    }
    '/shop/track': {
      id: '/shop/track'
      path: '/track'
      fullPath: '/shop/track'
      preLoaderRoute: typeof ShopTrackRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/review': {
      id: '/shop/review'
      path: '/review'
      fullPath: '/shop/review'
      preLoaderRoute: typeof ShopReviewRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/payment': {
      id: '/shop/payment'
      path: '/payment'
      fullPath: '/shop/payment'
      preLoaderRoute: typeof ShopPaymentRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/order': {
      id: '/shop/order'
      path: '/order'
      fullPath: '/shop/order'
      preLoaderRoute: typeof ShopOrderRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/delivered': {
      id: '/shop/delivered'
      path: '/delivered'
      fullPath: '/shop/delivered'
      preLoaderRoute: typeof ShopDeliveredRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/confirmed': {
      id: '/shop/confirmed'
      path: '/confirmed'
      fullPath: '/shop/confirmed'
      preLoaderRoute: typeof ShopConfirmedRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/address': {
      id: '/shop/address'
      path: '/address'
      fullPath: '/shop/address'
      preLoaderRoute: typeof ShopAddressRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/added': {
      id: '/shop/added'
      path: '/added'
      fullPath: '/shop/added'
      preLoaderRoute: typeof ShopAddedRouteImport
      parentRoute: typeof ShopRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personal': {
      id: '/settings/personal'
      path: '/personal'
      fullPath: '/settings/personal'
      preLoaderRoute: typeof SettingsPersonalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/new': {
      id: '/reminders/new'
      path: '/new'
      fullPath: '/reminders/new'
      preLoaderRoute: typeof RemindersNewRouteImport
      parentRoute: typeof RemindersRoute
    }
    '/reminders/calendar': {
      id: '/reminders/calendar'
      path: '/calendar'
      fullPath: '/reminders/calendar'
      preLoaderRoute: typeof RemindersCalendarRouteImport
      parentRoute: typeof RemindersRoute
    }
    '/reminders/$id': {
      id: '/reminders/$id'
      path: '/$id'
      fullPath: '/reminders/$id'
      preLoaderRoute: typeof RemindersIdRouteImport
      parentRoute: typeof RemindersRoute
    }
    '/recommendations/share': {
      id: '/recommendations/share'
      path: '/share'
      fullPath: '/recommendations/share'
      preLoaderRoute: typeof RecommendationsShareRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/recommendations/save': {
      id: '/recommendations/save'
      path: '/save'
      fullPath: '/recommendations/save'
      preLoaderRoute: typeof RecommendationsSaveRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/recommendations/routine': {
      id: '/recommendations/routine'
      path: '/routine'
      fullPath: '/recommendations/routine'
      preLoaderRoute: typeof RecommendationsRoutineRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/recommendations/products': {
      id: '/recommendations/products'
      path: '/products'
      fullPath: '/recommendations/products'
      preLoaderRoute: typeof RecommendationsProductsRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/history/compare': {
      id: '/history/compare'
      path: '/compare'
      fullPath: '/history/compare'
      preLoaderRoute: typeof HistoryCompareRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/favorites/routines': {
      id: '/favorites/routines'
      path: '/routines'
      fullPath: '/favorites/routines'
      preLoaderRoute: typeof FavoritesRoutinesRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/products': {
      id: '/favorites/products'
      path: '/products'
      fullPath: '/favorites/products'
      preLoaderRoute: typeof FavoritesProductsRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/experts': {
      id: '/favorites/experts'
      path: '/experts'
      fullPath: '/favorites/experts'
      preLoaderRoute: typeof FavoritesExpertsRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/collections': {
      id: '/favorites/collections'
      path: '/collections'
      fullPath: '/favorites/collections'
      preLoaderRoute: typeof FavoritesCollectionsRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/articles': {
      id: '/favorites/articles'
      path: '/articles'
      fullPath: '/favorites/articles'
      preLoaderRoute: typeof FavoritesArticlesRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/tips/experts/$id': {
      id: '/tips/experts/$id'
      path: '/$id'
      fullPath: '/tips/experts/$id'
      preLoaderRoute: typeof TipsExpertsIdRouteImport
      parentRoute: typeof TipsExpertsRoute
    }
    '/tips/article/$slug': {
      id: '/tips/article/$slug'
      path: '/article/$slug'
      fullPath: '/tips/article/$slug'
      preLoaderRoute: typeof TipsArticleSlugRouteImport
      parentRoute: typeof TipsRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/payment/card': {
      id: '/shop/payment/card'
      path: '/card'
      fullPath: '/shop/payment/card'
      preLoaderRoute: typeof ShopPaymentCardRouteImport
      parentRoute: typeof ShopPaymentRoute
    }
    '/reminders/$id/snooze': {
      id: '/reminders/$id/snooze'
      path: '/snooze'
      fullPath: '/reminders/$id/snooze'
      preLoaderRoute: typeof RemindersIdSnoozeRouteImport
      parentRoute: typeof RemindersIdRoute
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/experts': {
      id: '/_authenticated/admin/experts'
      path: '/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AuthenticatedAdminExpertsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports/': {
      id: '/_authenticated/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AuthenticatedAdminReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports/$id': {
      id: '/_authenticated/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AuthenticatedAdminReportsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminExpertsRoute: typeof AuthenticatedAdminExpertsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminReportsIdRoute: typeof AuthenticatedAdminReportsIdRoute
  AuthenticatedAdminReportsIndexRoute: typeof AuthenticatedAdminReportsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminExpertsRoute: AuthenticatedAdminExpertsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminReportsIdRoute: AuthenticatedAdminReportsIdRoute,
  AuthenticatedAdminReportsIndexRoute: AuthenticatedAdminReportsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FavoritesRouteChildren {
  FavoritesArticlesRoute: typeof FavoritesArticlesRoute
  FavoritesCollectionsRoute: typeof FavoritesCollectionsRoute
  FavoritesExpertsRoute: typeof FavoritesExpertsRoute
  FavoritesProductsRoute: typeof FavoritesProductsRoute
  FavoritesRoutinesRoute: typeof FavoritesRoutinesRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
}

const FavoritesRouteChildren: FavoritesRouteChildren = {
  FavoritesArticlesRoute: FavoritesArticlesRoute,
  FavoritesCollectionsRoute: FavoritesCollectionsRoute,
  FavoritesExpertsRoute: FavoritesExpertsRoute,
  FavoritesProductsRoute: FavoritesProductsRoute,
  FavoritesRoutinesRoute: FavoritesRoutinesRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
}

const FavoritesRouteWithChildren = FavoritesRoute._addFileChildren(
  FavoritesRouteChildren,
)

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryCompareRoute: typeof HistoryCompareRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
  HistoryCompareRoute: HistoryCompareRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface RecommendationsRouteChildren {
  RecommendationsProductsRoute: typeof RecommendationsProductsRoute
  RecommendationsRoutineRoute: typeof RecommendationsRoutineRoute
  RecommendationsSaveRoute: typeof RecommendationsSaveRoute
  RecommendationsShareRoute: typeof RecommendationsShareRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
}

const RecommendationsRouteChildren: RecommendationsRouteChildren = {
  RecommendationsProductsRoute: RecommendationsProductsRoute,
  RecommendationsRoutineRoute: RecommendationsRoutineRoute,
  RecommendationsSaveRoute: RecommendationsSaveRoute,
  RecommendationsShareRoute: RecommendationsShareRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
}

const RecommendationsRouteWithChildren = RecommendationsRoute._addFileChildren(
  RecommendationsRouteChildren,
)

interface RemindersIdRouteChildren {
  RemindersIdSnoozeRoute: typeof RemindersIdSnoozeRoute
}

const RemindersIdRouteChildren: RemindersIdRouteChildren = {
  RemindersIdSnoozeRoute: RemindersIdSnoozeRoute,
}

const RemindersIdRouteWithChildren = RemindersIdRoute._addFileChildren(
  RemindersIdRouteChildren,
)

interface RemindersRouteChildren {
  RemindersIdRoute: typeof RemindersIdRouteWithChildren
  RemindersCalendarRoute: typeof RemindersCalendarRoute
  RemindersNewRoute: typeof RemindersNewRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
}

const RemindersRouteChildren: RemindersRouteChildren = {
  RemindersIdRoute: RemindersIdRouteWithChildren,
  RemindersCalendarRoute: RemindersCalendarRoute,
  RemindersNewRoute: RemindersNewRoute,
  RemindersIndexRoute: RemindersIndexRoute,
}

const RemindersRouteWithChildren = RemindersRoute._addFileChildren(
  RemindersRouteChildren,
)

interface SettingsRouteChildren {
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPersonalRoute: typeof SettingsPersonalRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPersonalRoute: SettingsPersonalRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ShopPaymentRouteChildren {
  ShopPaymentCardRoute: typeof ShopPaymentCardRoute
}

const ShopPaymentRouteChildren: ShopPaymentRouteChildren = {
  ShopPaymentCardRoute: ShopPaymentCardRoute,
}

const ShopPaymentRouteWithChildren = ShopPaymentRoute._addFileChildren(
  ShopPaymentRouteChildren,
)

interface ShopRouteChildren {
  ShopAddedRoute: typeof ShopAddedRoute
  ShopAddressRoute: typeof ShopAddressRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopConfirmedRoute: typeof ShopConfirmedRoute
  ShopDeliveredRoute: typeof ShopDeliveredRoute
  ShopOrderRoute: typeof ShopOrderRoute
  ShopPaymentRoute: typeof ShopPaymentRouteWithChildren
  ShopReviewRoute: typeof ShopReviewRoute
  ShopTrackRoute: typeof ShopTrackRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAddedRoute: ShopAddedRoute,
  ShopAddressRoute: ShopAddressRoute,
  ShopCartRoute: ShopCartRoute,
  ShopConfirmedRoute: ShopConfirmedRoute,
  ShopDeliveredRoute: ShopDeliveredRoute,
  ShopOrderRoute: ShopOrderRoute,
  ShopPaymentRoute: ShopPaymentRouteWithChildren,
  ShopReviewRoute: ShopReviewRoute,
  ShopTrackRoute: ShopTrackRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface TipsExpertsRouteChildren {
  TipsExpertsIdRoute: typeof TipsExpertsIdRoute
}

const TipsExpertsRouteChildren: TipsExpertsRouteChildren = {
  TipsExpertsIdRoute: TipsExpertsIdRoute,
}

const TipsExpertsRouteWithChildren = TipsExpertsRoute._addFileChildren(
  TipsExpertsRouteChildren,
)

interface TipsRouteChildren {
  TipsBasicsRoute: typeof TipsBasicsRoute
  TipsCategoriesRoute: typeof TipsCategoriesRoute
  TipsConcernsRoute: typeof TipsConcernsRoute
  TipsExpertsRoute: typeof TipsExpertsRouteWithChildren
  TipsIngredientsRoute: typeof TipsIngredientsRoute
  TipsIndexRoute: typeof TipsIndexRoute
  TipsArticleSlugRoute: typeof TipsArticleSlugRoute
}

const TipsRouteChildren: TipsRouteChildren = {
  TipsBasicsRoute: TipsBasicsRoute,
  TipsCategoriesRoute: TipsCategoriesRoute,
  TipsConcernsRoute: TipsConcernsRoute,
  TipsExpertsRoute: TipsExpertsRouteWithChildren,
  TipsIngredientsRoute: TipsIngredientsRoute,
  TipsIndexRoute: TipsIndexRoute,
  TipsArticleSlugRoute: TipsArticleSlugRoute,
}

const TipsRouteWithChildren = TipsRoute._addFileChildren(TipsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRouteWithChildren,
  HistoryRoute: HistoryRouteWithChildren,
  RecommendationsRoute: RecommendationsRouteWithChildren,
  RemindersRoute: RemindersRouteWithChildren,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TipsRoute: TipsRouteWithChildren,
  STokenRoute: STokenRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
